### ISSUE TITLE
Display correct online status of contacts

### ISSUE THREAD

**Issue by delvh** [informatik-ag-ngl/envoy-client#152]
When a user logs in, he is not notified of the current status of his contacts, even though a contact list is already getting sent to him.

1. Log-in
2. Enjoy.

![grafik](https://user-images.githubusercontent.com/51889757/85434093-ccd4d700-b585-11ea-9548-6c9a763228ca.png)

**Comment by CyB3RC0nN0R** [comment]
I have fixed this bug locally, but it is an inefficient and hacky solution. Before creating a pull request for it, I'll try to solve the problem in a more elegant way.
