### ISSUE TITLE
Post Button State after Copy and Post

### ISSUE THREAD

**Issue by DieGurke** [informatik-ag-ngl/envoy-client#165]
When a text is copied into the message text area, the post button stays disabled and the char count does not decrease.

**Comment by CyB3RC0nN0R** [comment]
It works fine on the development build, is it possible that you are working on an outdated branch?

**Comment by CyB3RC0nN0R** [comment]
If you are sure that the bug is still present, please provide some screenshots and steps for reproduction so we can follow along.
