### ISSUE TITLE
Should message order be restored after offline mode?

### ISSUE THREAD

**Issue by CyB3RC0nN0R** [informatik-ag-ngl/envoy-client#168]
When a message is sent from offline mode, subsequently received messages are displayed below it, even if they were sent earlier in time (look into #167 for screenshots).

This is obviously expected given the current synchronization logic, but should it be changed? We could insert received messages according to their creation timestamp, however I am not sure if that's a good idea.

**Comment by delvh** [comment]
I'd say so. Users want to be have their chat in the correct order. However, I'd also say that this issue is closely related to the issue of displaying the amount of pending messages.

**Comment by CyB3RC0nN0R** [comment]
> 
> 
> I'd say so. Users want to have their chat in the correct order. However, I'd also say that this issue is closely related to the issue of displaying the amount of pending messages.

Allright, I will get to work then.
