### ISSUE TITLE
StatusTrayIcon does not work on Linux

### ISSUE THREAD

**Issue by delvh** [informatik-ag-ngl/envoy-client#46]
one solution would be to throw an error if not supported and only allow otherwise.

**Comment by CyB3RC0nN0R** [comment]
I like your suggestion of a silent failure in case of the system tray not being supported on a platform. I would still log a warning in that case, but not display anything to the user as this does not affect the core functionality of our application.
This would obviously prevent message notifications from being shown as the `StatusTrayIcon` would not register itself as an event listener.
