### ISSUE TITLE
Further checks before creating a own theme

### ISSUE THREAD

**Issue by delvh** [informatik-ag-ngl/envoy-client#79]
Currently we just let the user change the name of a new theme when creating it. This should be fixed as it can it lead to name collision. 
To suppress this we should implement a loop that checks if any currently existing theme is named as the new Theme and if yes, we give the user the chance to either override the existing one or to (automatically) rename it.

**Comment by CyB3RC0nN0R** [comment]
We have `Map.containsKey(String)` for this.

**Comment by DieGurke** [comment]
Im currently working on this
