### ISSUE TITLE
Remove Themes

### ISSUE THREAD

**Issue by DieGurke** [informatik-ag-ngl/envoy-client#86]
Removing themes. (But not currently active one) -> Always at least one theme remaining

**Comment by CyB3RC0nN0R** [comment]
We should also check if the user tries to remove one of the default themes (dark and light), which should be prohibited as they would be resetted after an application restart.

**Comment by DieGurke** [comment]
And we should also block the ability to overwrite these default themes

**Comment by CyB3RC0nN0R** [comment]
Themes will be reimplemented as outlined in #133, so this will be worked on in the context of that feature.
