### ISSUE TITLE
Component List

### ISSUE THREAD

**Issue by delvh** [informatik-ag-ngl/envoy-client#90]
We need a component that allows freely interacting with values in it but can be used at the same time to store multiple instances, basically a List of JPanels.

**Comment by CyB3RC0nN0R** [comment]
For this we basically have two options:

- Find a way of storing `JPanel`s inside a `JList` and letting the user interact with them

- Create the component by ourselves using a list-like `LayoutManager`

I will investigate this in the upcoming days.

**Comment by CyB3RC0nN0R** [comment]
I have started working on a custom Swing component called `ComponentList` on `f/component_list`. This component will have an interface similar to the `JList` with a `ComponentListModel` and a `ComponentListCellRenderer`, however the functionality will be limited to whatever we need at the moment.
